# Generated by Django 5.1.7 on 2025-03-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedDocument',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('word_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sections', models.JSONField(default=list)),
                ('references', models.JSONField(default=list)),
                ('paper_summaries', models.JSONField(default=list)),
                ('process_logs', models.JSONField(default=list)),
                ('search_terms', models.JSONField(default=list)),
                ('citations', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
